server {
    listen 80;
    listen [::]:80;

    server_name localhost;
    root /usr/share/webapps;  # общий корень для всех веб-приложений

    index index.php;

    # Доступ к Adminer через /adminer
    location /admin {
        try_files $uri $uri/ /adminer/index.php?$query_string;
    }

    # PHP обработка
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock; # путь к PHP-FPM сокету
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
 
