services:
  db:
    image: postgres:17
    container_name: podcast_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: podcast_test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podcast_tests
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.test
    volumes:
      - ./allure-report:/app/allure-report
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
