
worker_processes  20;

# error_log /var/log/nginx/error.log debug;

include modules.d/*.conf;

events {
    worker_connections  1024;
    multi_accept on;
}


http {
    include       mime.types;
    include /etc/nginx/adminer.conf;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;


    server {
        listen       80;
        server_name  localhost;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # podcast

        location /api/v1/ {
            proxy_pass http://localhost:32482/api/v1/;
        }

        location = /api/v1 {
            proxy_pass http://localhost:32482/api/v1/documentation;
        }
        
        location = /api/v1/json {
            rewrite ^ /api/v1/documentation/json break;
            proxy_pass http://localhost:32482;
        }
        
        location /legacy/ {
            alias /usr/share/nginx/static/build/;
            index index.html;
        }

        location /documentation {
            alias /usr/share/nginx/static;
            index documentation.html;
        }

        location /admin {
            proxy_pass http://127.0.0.1:8080/admin;
        }

        location / {
            root /usr/share/nginx/static;
            try_files $uri $uri/ =404;
        }

        location /reserved/ {
            alias /usr/share/nginx/static/;
            try_files $uri $uri/ =404;
            index index.html;
        }

        location /stab_status {
            stub_status;
        }

        location /status/ {
            alias /usr/share/nginx/static/status/;
            index index.html;
            try_files $uri $uri/ /status/index.html;
        }
        
        location /management {
            alias /usr/share/nginx/static;
            index management.html;
        }
    }
}
