openapi: 3.1.1
info:
  title: Podcast stream service
  version: 0.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
paths:
  /api/v1/sessions:
    post:
      summary: log in
      tags:
        - sessions
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  minLength: 1
                  type: string
              required:
                - login
                - password
        required: true
      responses:
        "201":
          description: Default Response
          headers:
            refresh_token:
              schema:
                type: string
              description: http-only cookie
          content:
            application/json:
              schema:
                type: object
                properties: {}
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
    delete:
      summary: log out
      tags:
        - sessions
      parameters:
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Default Response
  /api/v1/sessions/access_token:
    post:
      summary: get access token
      tags:
        - sessions
      parameters:
        - schema:
            type: string
          in: header
          name: refresh_token
          required: true
          description: http-only cookie
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
  /api/v1/podcasts:
    get:
      summary: search podcasts by query
      tags:
        - podcasts
      parameters:
        - schema:
            type: string
          in: query
          name: query
          required: false
        - schema:
            minimum: 1
            type: integer
          in: query
          name: page
          required: false
        - schema:
            minimum: 1
            type: integer
          in: query
          name: podcasts_per_page
          required: false
        - schema:
            type: string
          in: query
          name: url
          required: false
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  podcasts:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        platform:
                          type: string
                        duration_s:
                          minimum: 1
                          type: integer
                        relevance:
                          type: string
                        url:
                          type: string
                      required:
                        - title
                        - platform
                        - duration_s
                        - relevance
                        - url
                  pagination:
                    type: object
                    properties:
                      page:
                        minimum: 1
                        type: integer
                      podcasts_per_page:
                        minimum: 1
                        type: integer
                      total_podcasts:
                        minimum: 1
                        type: integer
                    required:
                      - page
                      - podcasts_per_page
                      - total_podcasts
                required:
                  - podcasts
                  - pagination
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/v1/users/channels:
    get:
      summary: get array of user subscriptions
      tags:
        - users
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: query
          name: page
          required: true
        - schema:
            minimum: 1
            type: integer
          in: query
          name: channels_per_page
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          minimum: 1
                          type: integer
                        url:
                          type: string
                        title:
                          type: string
                        platform:
                          type: string
                      required:
                        - id
                        - url
                        - title
                        - platform
                  pagination:
                    type: object
                    properties:
                      page:
                        minimum: 1
                        type: integer
                      channels_per_page:
                        minimum: 1
                        type: integer
                      total_channels:
                        minimum: 1
                        type: integer
                    required:
                      - page
                      - channels_per_page
                      - total_channels
                required:
                  - channels
                  - pagination
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
    post:
      summary: subscribe to channel
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                channel_title:
                  type: string
                channel_url:
                  type: string
              required:
                - channel_title
                - channel_url
        required: true
      parameters:
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    minimum: 1
                    type: integer
                  url:
                    type: string
                  title:
                    type: string
                  platform:
                    type: string
                required:
                  - id
                  - url
                  - title
                  - platform
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/v1/users/contents:
    get:
      summary: get feed content
      tags:
        - users
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: query
          name: page
          required: true
        - schema:
            minimum: 1
            type: integer
          in: query
          name: podcasts_per_page
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  podcasts:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        platform:
                          type: string
                        duration_s:
                          minimum: 1
                          type: integer
                        relevance:
                          type: string
                        url:
                          type: string
                      required:
                        - title
                        - platform
                        - duration_s
                        - relevance
                        - url
                  pagination:
                    type: object
                    properties:
                      page:
                        minimum: 1
                        type: integer
                      podcasts_per_page:
                        minimum: 1
                        type: integer
                      total_podcasts:
                        minimum: 1
                        type: integer
                    required:
                      - page
                      - podcasts_per_page
                      - total_podcasts
                required:
                  - podcasts
                  - pagination
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/v1/users/channels/{id}:
    delete:
      summary: unsubscribe from channel
      tags:
        - users
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: path
          name: id
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Default Response
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
    get:
      summary: get subscription by id
      tags:
        - users
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: path
          name: id
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    minimum: 1
                    type: integer
                  url:
                    type: string
                  title:
                    type: string
                  platform:
                    type: string
                required:
                  - id
                  - url
                  - title
                  - platform
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
    put:
      summary: update subscription information
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                title:
                  type: string
                platform:
                  type: string
              required:
                - url
                - title
                - platform
        required: true
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: path
          name: id
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    minimum: 1
                    type: integer
                  url:
                    type: string
                  title:
                    type: string
                  platform:
                    type: string
                required:
                  - id
                  - url
                  - title
                  - platform
        "204":
          description: Default Response
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
    patch:
      summary: update subscription title
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
        required: true
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: path
          name: id
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    minimum: 1
                    type: integer
                  url:
                    type: string
                  title:
                    type: string
                  platform:
                    type: string
                required:
                  - id
                  - url
                  - title
                  - platform
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/v1/streams:
    get:
      summary: get podcast audio
      tags:
        - stream
      parameters:
        - schema:
            type: string
          in: query
          name: url
          required: true
        - schema:
            type: string
          in: header
          name: access_token
          required: true
          description: bearer token for authorization
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            audio/mpeg:
              schema:
                description: audio response
                type: string
                format: binary
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
