openapi: 3.1.1
info:
  title: Podcast stream service
  version: 0.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  minLength: 1
                  type: string
              required:
                - login
                - password
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                required:
                  - result
  /get_access_token:
    post:
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
  /logout:
    delete:
      responses:
        "200":
          description: Default Response
  /:
    get:
      summary: home page
      tags:
        - static
      responses:
        "200":
          description: File content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /api/podcast/results:
    get:
      summary: search podcasts by query
      tags:
        - podcast
      parameters:
        - schema:
            type: string
          in: query
          name: query
          required: true
        - schema:
            minimum: 1
            type: integer
          in: query
          name: max_results
          required: true
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    platform:
                      type: string
                    duration_s:
                      minimum: 1
                      type: integer
                    relevance:
                      type: string
                    url:
                      type: string
                  required:
                    - title
                    - platform
                    - duration_s
                    - relevance
                    - url
  /api/podcast/result:
    get:
      summary: search podcast by url
      tags:
        - podcast
      parameters:
        - schema:
            type: string
          in: query
          name: url
          required: true
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  platform:
                    type: string
                  duration_s:
                    minimum: 1
                    type: integer
                  relevance:
                    type: string
                  url:
                    type: string
                required:
                  - title
                  - platform
                  - duration_s
                  - relevance
                  - url
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/user/subscriptions:
    get:
      summary: get array of user subscriptions
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      minimum: 1
                      type: integer
                    url:
                      type: string
                    title:
                      type: string
                    platform:
                      type: string
                  required:
                    - id
                    - url
                    - title
                    - platform
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/user/feed/content:
    get:
      summary: get feed content
      tags:
        - user
        - feed
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: query
          name: feed_size
          required: false
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    platform:
                      type: string
                    duration_s:
                      minimum: 1
                      type: integer
                    relevance:
                      type: string
                    url:
                      type: string
                  required:
                    - title
                    - platform
                    - duration_s
                    - relevance
                    - url
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/user/channel/subscribe:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: channel_title
          required: true
        - schema:
            type: string
          in: query
          name: channel_url
          required: true
      responses:
        "200":
          description: Default Response
  /api/user/channel/unsubscribe:
    get:
      parameters:
        - schema:
            minimum: 1
            type: integer
          in: query
          name: channel_id
          required: true
      responses:
        "200":
          description: Default Response
  /api/stream:
    get:
      summary: get podcast audio
      tags:
        - stream
      parameters:
        - schema:
            type: string
          in: query
          name: url
          required: true
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Default Response
          content:
            audio/mpeg:
              schema:
                description: audio response
                type: string
                format: binary
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
