name: Podcast CI/DI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v4

  #     - name: Run unit tests in Docker
  #       working-directory: ./app
  #       run: docker compose run tests -u

  #     - name: Upload artifacts
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: unit-results
  #         path: ./app/junit_report

  #     - name: Stop services
  #       working-directory: ./app
  #       if: always()
  #       run: docker compose down

  # integration-tests:
  #   needs: unit-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v4

  #     - name: Run integration tests in Docker
  #       working-directory: ./app
  #       run: docker compose run tests -i

  #     - name: Upload artifacts
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: integration-results
  #         path: ./app/junit_report

  #     - name: Stop services
  #       working-directory: ./app
  #       if: always()
  #       run: docker compose down

  e2e-tests:
    # needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Run e2e tests in Docker
        working-directory: ./app
        run: docker compose run -e YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} tests --end_to_end

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: ./app/allure-results

      - name: Stop services
        working-directory: ./app
        if: always()
        run: docker compose down

  # generate-allure:
  #   needs: [unit-tests, integration-tests, e2e-tests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: unit-results
  #         path: ./all-results/unit
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: integration-results
  #         path: ./all-results/integration
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: e2e-results
  #         path: ./all-results/e2e
  #     - run: |
  #         mkdir -p ./all-results/merged
  #         cp -r ./all-results/unit/* ./all-results/merged/
  #         cp -r ./all-results/integration/* ./all-results/merged/
  #         cp -r ./all-results/e2e/* ./all-results/merged/
  #     - name: Install Allure
  #       run: npm install -g allure-commandline --save-dev
  #     - run: allure generate ./all-results/merged --clean -o ./allure-report --single-file
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: final-allure-report
  #         path: ./allure-report
